name: my-first-workflow
#to get trigger on every push is this repo in my branch 
on: push
jobs:
  job1 :
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: Running single command in Job1
        run: echo "hi, this is my first GitHub Workflow"
      - name: Checking  OS Release for GitHub Hosted runner
        run: cat /etc/os-release
      - name: Calling Sleeping
        run: sleep 20
      
  job2:
     name: JOB2
     runs-on: ubuntu-latest
     steps:
       - name: Checking the Hostname for Runner
         run: hostname
       - name: Running multiple commands
         run: 
           echo "Hi from arezou "
           echo "current time is  'date'"
           sleep 20
