name: my-first-workflow
#to get trigger on every push is this repo in my branch 
on:
  push: 
jobs:
  job1 :
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: |
          pwd
          ls -ltr
          hostname
      - name: step-2 - checkout
        uses: actions/checkout@v6.0.2
      - name: step-3
        run: |
          echo pwd >>  myartifact.txt
          mkdir artifacts
          ls -ltr >> artifacts/list.txt
          hostname >> artifacts/hostname.txt
      - name: Upload Single file
        uses: actions/upload-artifact@v4
        with:
          name: single_file
          path: ./myartifact.txt
  
      - name: Upload from directory
        uses: actions/upload-artifact@v4
        with:
          name: directory-artifacts
          path: artifacts/
      - name: Upload from multiple paths
        uses: actions/upload-artifact@v4
        with:
          name: multiple_path
          path: | 
           ./myartifact
           artifacts/
      - name: Upload from multiple paths with exclusion
        uses: actions/upload-artifact@v4
        with:
         name: multiple_path_exclusions
         path: | 
          ./myartifact
          artifacts/
          !**/hostname.txt
          
        
